### ISSUE TITLE
BS is not able to handle formatter logging in the github actions using BS sdk 

### ISSUE THREAD

**Issue by NurlanMirovich** [browserstack/github-actions#41]
When configuring logging in pytest the github actions are throwing BS logs 

BS is not able to handle the logging level -> also have pytest.ini config file 

![image](https://github.com/browserstack/github-actions/assets/160641374/2a5ccaab-c720-4625-9cad-20290fd69626)

![image](https://github.com/browserstack/github-actions/assets/160641374/579584b7-a53f-4ded-aa62-fe86e336bd96)

![image](https://github.com/browserstack/github-actions/assets/160641374/76a29e2c-7e03-488f-a444-e2bf4b7b81a0)

![image](https://github.com/browserstack/github-actions/assets/160641374/f6cc8267-d3b9-402a-bdb3-927d7e462868)

**Comment by NurlanMirovich** [comment]
There is still one more issue with the custom formatted log's / once the logger configurations are added there is error from the BS 

![image](https://github.com/browserstack/github-actions/assets/160641374/bdc624b7-9991-4a17-acc8-c5712743baaf)
![image](https://github.com/browserstack/github-actions/assets/160641374/4995ce6d-988d-48a2-ba74-5e4154f7cd4b)
![image](https://github.com/browserstack/github-actions/assets/160641374/c68b39f6-f9dd-4da7-9034-71238d741021)




![image](https://github.com/browserstack/github-actions/assets/160641374/c22471dc-6c81-4ca6-827c-65c25e3025a9)

![image](https://github.com/browserstack/github-actions/assets/160641374/420f8ed8-81c9-4d60-8934-fa222feab744)

**Comment by NurlanMirovich** [comment]
@1114204

**Comment by NurlanMirovich** [comment]
@nakula @raunakpilani @kalamcs @punitx Could you please take a look at it when have chance ?

**Comment by NurlanMirovich** [comment]
Throwing all BS logs my way 
![image](https://github.com/browserstack/github-actions/assets/160641374/ac5a8e44-a094-4ec1-99c4-d7a392e995a4)

![image](https://github.com/browserstack/github-actions/assets/160641374/fd71979c-388d-43cd-acf9-ce950b04158f)

**Comment by karanshah-browserstack** [comment]
@NurlanMirovich We are checking into the issue, and we will get back with an update soon.

**Comment by NurlanMirovich** [comment]
@karanshah-browserstack Thank you !

**Comment by NurlanMirovich** [comment]
Hi @karanshah-browserstack have this issue been fixed yet

**Comment by samarsault** [comment]
Hi @NurlanMirovich we're looking into the issue, please give us some time to fix this

**Comment by sriteja777** [comment]
@NurlanMirovich This issue is fixed in the latest version of BrowserStack SDK `1.19.23`. Can you please upgrade `browserstack-sdk` python package to this version and check once?

**Comment by NurlanMirovich** [comment]
Hi @sriteja777 @samarsault @karanshah-browserstack 
I have updated my requirements to 

And i test in local and pipeline, but this is still not wokring, i will include my pytest logs configurations so that you can reproduce 



<img width="382" alt="image" src="https://github.com/browserstack/github-actions/assets/160641374/e727db95-426a-4e1b-b3f9-566dd4e9e94b">

<img width="1453" alt="image" src="https://github.com/browserstack/github-actions/assets/160641374/ca169c69-1e9d-467c-af98-c84adfdc75b5">

<img width="1205" alt="image" src="https://github.com/browserstack/github-actions/assets/160641374/42d9c6ed-e186-46d1-8964-60a2ed0c009d">


Here is my pytest.ini file 
<img width="1054" alt="image" src="https://github.com/browserstack/github-actions/assets/160641374/05e4b4c3-8b69-47c0-bda2-0e4fb24b63db">


Here is my log files configuration 

"""
This module contains shared fixtures, steps, and hooks.
"""
import json
import os
from pytest_bdd import given, parsers, then, when
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from data.test_data import ENROLLMENT_BASE_URL
import logging
import pytest


class ColorFormatter(logging.Formatter):
    GREEN = "\033[92m"
    LIGHT_RED = "\033[91;1m"
    RED = "\033[91m"
    YELLOW = "\033[93m"
    RESET = "\033[0m"

    FORMATS = {
        # logging.DEBUG: LIGHT_RED + "%(message)s" + RESET,
        logging.INFO: GREEN + "%(message)s" + RESET,
        logging.WARNING: YELLOW + "%(levelname)s: %(message)s" + RESET,
        logging.ERROR: RED + "%(levelname)s: %(message)s" + RESET,
        logging.CRITICAL: RED + "%(levelname)s: %(message)s" + RESET,
    }

    def format(self, record):
        log_fmt = self.FORMATS.get(record.levelno)
        formatter = logging.Formatter(log_fmt)
        return formatter.format(record)


number_of_scenarios = []


@pytest.hookimpl
def pytest_bdd_before_scenario(scenario):
    number_of_scenarios.append(scenario.name)
    logging.info(f"[Scenario Name] - {scenario.name}")


@pytest.hookimpl
def pytest_bdd_after_scenario():
    logging.info(f"[Executed scenarios] - {number_of_scenarios}")


@pytest.hookimpl
def pytest_bdd_before_step(step):
    logging.info(f"[Step name] - {step.name}")


@pytest.fixture(scope="session", autouse=True)
def setup_logging():
    root_logger = logging.getLogger()
    root_logger.setLevel(logging.INFO)
    console_handler = logging.StreamHandler()
    console_handler.setFormatter(ColorFormatter())
    root_logger.addHandler(console_handler)


@pytest.fixture
def config(scope='session'):
    # Read the file
    with open('config.json') as config_file:
        config = json.load(config_file)

    # Accept values are acceptable
    assert config['browser'] in ['firefox', 'chrome', 'headless firefox', 'headless chrome']
    assert config['platform'] in ['desktop', 'mobile', 'ios', 'android']
    assert isinstance(config['timeout'], int)
    assert config['timeout'] > 0

    # Return config so it can be used
    return config


# This fixture will run once for each test case
@pytest.fixture
def driver(config):
    global driver
    driver = None

    if config['platform'] == 'desktop':

        if config["browser"] == "chrome":
            options = webdriver.ChromeOptions()
            options.add_argument("window-position=-1000,0")
            options.set_capability('goog:loggingPrefs', {'browser': 'ALL'})
            options.add_experimental_option("detach", True)  # keep the browser open after the test run
            prefs = {
                'autofill.profile_enabled': False
            }
            options.add_experimental_option('prefs', prefs)
            if config["headless_mode"] is True:
                options.add_argument("--headless")
            driver = webdriver.Chrome(options)
            driver.maximize_window()

        elif config["browser"] == "firefox":
            options = webdriver.FirefoxOptions()
            if config["headless_mode"] is True:
                options.headless = True
            driver = webdriver.Firefox(options)

        elif config["browser"] == "edge":
            options = webdriver.EdgeOptions()
            options.use_chromium = True
            if config["headless_mode"] is True:
                options.headless = True
            driver = webdriver.Edge(options)

        elif config["browser"] == "safari":
            options = webdriver.SafariOptions()
            if config["headless_mode"] is True:
                options.headless = True
            driver = webdriver.Safari(options)

    if config['platform'] == 'mobile':

        if config["browser"] == "chrome":
            options = webdriver.ChromeOptions()
            options.add_argument("window-position=753,92")
            options.add_argument("--window-size=414,896")  # dimensions of the Iphone XR
            options.set_capability('goog:loggingPrefs', {'browser': 'ALL'})
            options.add_experimental_option("detach", True)
            prefs = {
                'autofill.profile_enabled': False
            }
            options.add_experimental_option('prefs', prefs)
            options.add_argument('--disable-notifications')
            options.add_argument("--disable-infobars")
            options.add_argument("--disable-extensions")
            if config["headless_mode"] is True:
                options.add_argument("--headless")
            driver = webdriver.Chrome(options)

        else:
            raise Exception(f'Browser "{config["browser"]}" is not supported in local mode')

    yield driver
    driver.quit()


@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item):
    pytest_html = item.config.pluginmanager.getplugin("html")
    outcome = yield
    report = outcome.get_result()
    extra = getattr(report, "extra", [])
    if report.when == "call":
        # always add url to report
        extra.append(pytest_html.extras.url(driver.current_url))
        xfail = hasattr(report, "wasxfail")
        if (report.skipped and xfail) or (report.failed and not xfail):
            report_directory = os.path.dirname(item.config.option.htmlpath)
            file_name = report.nodeid.replace("::", "_") + ".png"
            destination_file = os.path.join(report_directory, file_name)
            driver.save_screenshot(destination_file)
            if file_name:
                html = '<div><img src="%s" alt="screenshot" style="width:300px;height=200px"' \
                       'onclick="window.open(this.src)" align="right"/></div>' % file_name
                # only add additional html on failure
                extra.append(pytest_html.extras.html(html))
        report.extra = extra


@pytest.fixture
def credentials():
    with open('credentials.json') as config_file:
        return json.load(config_file)


@given(parsers.parse('the {end_point} page is displayed'), target_fixture="driver")
def navigate_to_page(driver, end_point):
    driver.get(ENROLLMENT_BASE_URL + end_point)
    wait = WebDriverWait(driver, 30)
    wait.until(expected_conditions.url_contains(end_point))
    all_elements = By.TAG_NAME, "html"
    wait.until(expected_conditions.visibility_of_all_elements_located(all_elements))
    return driver

**Comment by sriteja777** [comment]
@NurlanMirovich If i understand correctly, the issue you are facing is that you are seeing debug logs from BrowserStack SDK in your Github Actions and also locally even though you have not enabled debug logs. Is my understanding correct?

If so, can you please check these things?
- Have you added `log_level: INFO` to `pytest.ini`?
- Can you try setting `logLevel: info` in `browserstack.yml`?
- Also can you try setting `disableAutoCaptureLogs: true` in `browserstack.yml` ?

Can you please check with above things? 

I have tried reproducing the issue with your pytest.ini and log formatter, but wasn't able to reproduce the issue. In my case, I didn't get any debug logs from BrowserStack SDK when I just set as `log_level: INFO` in pytest.ini

**Comment by sriteja777** [comment]
@NurlanMirovich The issue you are facing currently is fixed in 1.19.19 version of `browserstack-sdk` . Can you please upgrade your `browserstack-sdk` package to the latest 1.19.24 and try out once? 

Let me know if you want to quickly come on call to resolve this issue faster

**Comment by NurlanMirovich** [comment]
Hi @sriteja777 i should be able to jump on a call with you... i updated but still minor issues

**Comment by NurlanMirovich** [comment]
Ganesh, i have updated the requirements.txt to 23 and tried to run again... also i removed parallelRun from the BS yaml file 

![image](https://github.com/browserstack/github-actions/assets/160641374/c504ff82-018a-4118-8c9d-1094e5a84d1f)
![image](https://github.com/browserstack/github-actions/assets/160641374/cf51dfd0-9aad-47a8-be9f-233296e5a56e)
![image](https://github.com/browserstack/github-actions/assets/160641374/db6c77a2-db0d-46f7-bc1f-8b3326fa9d3a)
![image](https://github.com/browserstack/github-actions/assets/160641374/4c5b6166-f245-4568-88ed-d086c9ddb07c)
![image](https://github.com/browserstack/github-actions/assets/160641374/ce41b4dc-ad62-4763-9263-488b978c3a27)
